[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "./runner.sh"

[build]
target = "thumbv6m-none-eabi"
linker = "flip-link"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
]
